#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy_portfolio

- name: copy file to target servers
  copy:
    src: "{{ playbook_dir }}/../app/dist/" # playbook_dir = server_config_ansible
    dest: "/var/www/portfolio"
    owner: ubuntu
    group: ubuntu
    mode: '0755'