plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: role

hostnames:
  # - instance-id
  # - ip-address
  - private-ip-address

compose:
  ansible_host: public_ip_address